version: "3.7"
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./front:/front
    working_dir: /front
    command: npm start
    tty: true
    ports:
      - 3000:3000

